version: "3"
services:
  postgres:
    image: postgres:12.4-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dryan
      POSTGRES_PASSWORD: dryan
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  postgresql:
  postgresql_data:
