version: "3"
services:
  db:
    image: mysql:8.0.21
    container_name: mysql
    environment:
      MYSQL_DATABASE: "dryan"
      MYSQL_USER: "dryan"
      MYSQL_PASSWORD: "dryan"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    restart: always

# Names our volume
volumes:
  my-db: